package com.liverowing.liverowing.model.pm

/**
 * Created by henrikmalmberg on 2017-11-03.
 */

enum class ErgMachineType (val i: Int) {
    STATIC_D(0),
    STATIC_C(1),
    STATIC_A(2),
    STATIC_B(3),
    STATIC_E(4),
    SLIDES_C(5),
    SLIDES_D(6),
    SLIDES_E(7),
    STATIC_DYNAMIC(8),
    SLIDES_A(16),
    SLIDES_B(17),
    SLIDES_DYNAMIC(32),
    STATIC_DYNO(64),
    STATIC_SKI(128)
}

enum class WorkoutType {
    JUSTROW_NOSPLITS,
    JUSTROW_SPLITS,
    FIXEDDIST_NOSPLITS,
    FIXEDDIST_SPLITS,
    FIXEDTIME_NOSPLITS,
    FIXEDTIME_SPLITS,
    FIXEDTIME_INTERVAL,
    FIXEDDIST_INTERVAL,
    VARIABLE_INTERVAL,
    VARIABLE_UNDEFINEDREST_INTERVAL,
    FIXED_CALORIE,
    FIXED_WATTMINUTES
}

enum class IntervalType (val i: Int) {
    TIME(0),
    DIST(1),
    REST(2),
    TIMERESTUNDEFINED(3),
    DISTANCERESTUNDEFINED(4),
    RESTUNDEFINED(5),
    CAL(6),
    CALRESTUNDEFINED(7),
    WATTMINUTE(8),
    WATTMINUTERESTUNDEFINED(9),
    NONE(255)
}

enum class WorkoutState {
    WAITTOBEGIN,
    WORKOUTROW,
    COUNTDOWNPAUSE,
    INTERVALREST,
    INTERVALWORKTIME,
    INTERVALWORKDISTANCE,
    INTERVALRESTENDTOWORKTIME,
    INTERVALRESTENDTOWORKDISTANCE,
    INTERVALWORKTIMETOREST,
    INTERVALWORKDISTANCETOREST,
    WORKOUTEND,
    TERMINATE,
    WORKOUTLOGGED,
    REARM
}

enum class RowingState {
    INACTIVE,
    ACTIVE
}

enum class StrokeState {
    WAITING_FOR_WHEEL_TO_REACH_MIN_SPEED_STATE,
    WAITING_FOR_WHEEL_TO_ACCELERATE_STATE,
    DRIVING_STATE,
    DWELLING_AFTER_DRIVE_STATE,
    RECOVERY_STATE
}

enum class DurationType (val i: Int) {
    TIME(0),
    CALORIES(0x40),
    DISTANCE(0x80),
    WATTS(0xC0)
}